### ISSUE TITLE
Servers are not Saved

### ISSUE THREAD

**Issue by BlaneyXYZ** [SKCraft/SKMCLauncher#37]
When using the Launcher Servers are not saved to file, but with the Stock Launcher Severs are Saved.

**Comment by sk89q** [comment]
Your OS and launcher version?

i do not experience this bug.

**Comment by BlaneyXYZ** [comment]
Thanks for the quick reply, anyways
OS: Windows 8
Launcher: v3.3.1
Seems like it only happens when using the .exe version

**Comment by shane-smith** [comment]
I experience this same issue - with and without mods loaded.

Operating System: Windows 8 Professional x64
Launcher: Version 3.1.7-SNAPSHOT (relatively old build from just after the launcher's notice to update appeared, about to upgrade this to latest build to re-test)

I am using the .jar file directly, not the executable.

---

Now running on build #15-8d27f3e, and servers are saved correctly. Restarting the Minecraft client/launcher no longer wipes changes made to the server list. The bug is fixed.

**Comment by BlaneyXYZ** [comment]
oh sweet :)
