### ISSUE TITLE
Nicer GUI

### ISSUE THREAD

**Issue by tonybruess** [SKCraft/SKMCLauncher#46]
I think it would be really sweet to have a nice and pleasant GUI, perhaps something similar to SpoutCraft's launcher: http://cl.ly/image/0z2e2L0V3t0Y

Also, an option to disable the fancy GUI would be ideal.

**Comment by rmsy** [comment]
SpoutCraft's doesn't really look all that appealing to me. I rather like the minimalism offered by this launcher; I think it would kind of negate the whole point if it were gussied up.

**Comment by tonybruess** [comment]
While I agree that SpoutCraft's launcher may not be the most appealing, I think adding a nicer GUI would be a great enhancement. For users like yourself that enjoy the minimalistic feel, an option to turn off the GUI would be trivial.

**Comment by sk89q** [comment]
I've been wanting to add this for a while, but
- It'd be optional.
- It'd be primarily geared for servers.

So far I haven't because:
1. Putting controls on top of an image won't look great on all platforms, depending on what the OS and windowing toolkit (and theme...) is being used.
2. Making the controls extremely minimalist (like the Spout Launcher) isn't that pretty IMO. Not all the controls can so easily be made so minimal either.
3. Skinning everything is a lot of work -- not the graphics part so much as all the Java code needed to draw it all. In fact I don't know how to do it off my head.
4. The skins Java comes with for controls are terrible. They look like they were designed by programmers and they look like they are from the 90s.
5. I need... some place to put the news. It also has to blend in, and I'm not sure how easily I can do that at the moment. Maybe it's easy.

Nevertheless, I could just put some critical controls on an OS rendered bar below or above the big image and skirt the problem.

**Comment by ewized** [comment]
I designed this in Photoshop for a concept for my server but its sorta unrealistic right now. Its sorta cheesy based off of Window 8.
![970792_569724769734372_454428708_n 1](https://f.cloud.github.com/assets/1458852/629896/36659736-d17c-11e2-91fb-fffd1cbe3741.png)

**Comment by sk89q** [comment]
I put the current launcher drawing code in ClassicView (extends LauncherView). The LauncherFrame now could theoretically switch between views.

**Comment by tonybruess** [comment]
Nice work

**Comment by circuitbomb** [comment]
#!/bin/rant

Both technic and ftb's launchers, in my personal opinion, are rather terrible in terms of usability(technic - too much going on, weird pack selection) and look(ftb - I mean cmon, huge tabs  heavy inner and outer shadows...eye blistering button gradients...).

Default Java 'look and feels' are horrid, as mentioned before, which leaves the default OS look and feel the most optimal choice anyway (you can be fairly certain how it will look cross platform).  You could always program your own look and feel, but that seems like a whole lot more heavy lifting than you would want for an MC launcher.

To be fair, the SK launcher right now is superb (it looks good in windows 8, great in 7) - and has a very nice splash.  The launcher doesn't have to be glossy and plastered with background images and fancy fonts - you spend the least amount of time there anyway.  Desirable? Sure.  Needed? Not really.

**Comment by sk89q** [comment]
Oh, if I _do_ do it, I'd make sure that it looked good and didn't have the problems.

The launcher does, at the moment, look terrible on Mac OS X though, primarily because of Java.

**Comment by sk89q** [comment]
I have a pretty GUI coming soon.
