### ISSUE TITLE
Cannot extract error

### ISSUE THREAD

**Issue by jakimfett** [SKCraft/SKMCLauncher#56]
I'm building a custom modpack using the command line, and when I add the modpack's URL, the files download properly, but at the end I get an error message saying "Error occurred: Could not install to <modpack directory>config\someConfigFile.cfg: Do not know how to extract config/someConfigFile.cfg"

Is there a way to disable archiving of files for the entire build, via a command line flag? Or a way in the build config file to disable this?

**Comment by sk89q** [comment]
Is it possible to give me a bare minimum set of files that break?

It shouldn't be trying to extract a .cfg.

**Comment by jakimfett** [comment]
I'm currently getting this error when passing the launcher the URL "http://mc.picraft.com/bleeding/update.xml" to download. 

I'm building the above modpack with "java -cp SKMCLauncher.jar com.sk89q.lpbuilder.UpdateBuilder -dir ./source -out ./output -config build.xml", and it's returning this: http://mc.picraft.com/bleeding/package.xml

Note that all the non-jar files are inside "<archive></archive>" tags, where the working version (which I built by hand via the GUI) has them as "<file></file>", and doesn't remove uppercases: http://www.picraft.com/pitek/package.xml

My build script and build XML file are available here: http://subversion.onkoistudios.com/pitek/client/, and the Jenkins instance that I'm building these with (via the buildScript.sh file in the subversion repo) is at http://mc.picraft.com/build/

Let me know if there's any more info you need. My apologies for not having a smaller modpack to throw your direction, I'm on the road, and don't have the time to hack anything together for you. 

EDIT: Fixing the link to the properly formatted package.xml

**Comment by sk89q** [comment]
I found the problem, and it was really dumb. I'm surprised that I didn't catch it.

The .zip name parameter was mixed around with the relative path of the file (`addFile(zip, path)` versus `addFile(path, zip)`). So this is what happened:
- Expected:
  - Contents `~/ModPack/configs/Whatever.cfg`
  - Went into: `~/OutputDir/configs.zip`
  - As: `configs/Whatever.cfg` (inside the zip)
- What happened:
  - Contents `~/ModPack/configs/Whatever.cfg`
  - Went into: `~/OutputDir/configs/whatever.cfg` (a zip file!)
  - As: `configs.zip` (inside the zip)

The lowercase thing was unrelated, but it did help me track down the problem. I just lowercased .zip file names, but since the file's path became the zip name, it was lowercased and it looked like the file's name itself was being modified.

I know it was a regression from when I added the _SERVER/_CLIENT thing.
