### ISSUE TITLE
Suggestion: RSS/Atom feed parser for custom news?

### ISSUE THREAD

**Issue by FabianN** [SKCraft/SKMCLauncher#61]
From what I read it sounds like you're doing a massive re-write for the launcher. While you're at it, would it be too much to ask for some kind of feed parser for the custom modpack news URLs? In the current version, since it's not a full fledged browser, many wordpress theme options break horribly, and it doesn't seem to be able to parse feeds.

Just a simple and clean feed parser to emulate how you have the default news displayed would be amazingly helpful in providing a nice experience for the players.

**Comment by sk89q** [comment]
I plan to use a better browser, which would let you do cooler things.

However, you probably wouldn't be able to just toss a WordPress URL into it because the HTML render I'm using requires XHTML and is fairly stringent about syntax.

![MC Launcher](http://i.imgur.com/WZZRqKK.jpg)

![GTA V](http://i.imgur.com/BSQIn7e.jpg)

**Comment by ewized** [comment]
Wow that look very cool, keep up the good work sk.
